### ISSUE TITLE
Container won't start when building the Docker image and running it

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/reveal-md#4]
```
$ docker build -t containersol/reveal-md:latest .
...
```

```
$ docker run -d -p 8000:1948 containersol/reveal-md -v $PWD/slides.md:/usr/src/app/slides.md
668ca4b9106c7448db779eccfc27d55cd7485fb0fac2680be90f914a10b9723e
```

```$ docker logs 668
/usr/lib/node_modules/reveal-md/node_modules/serve-static/index.js:40
    throw new TypeError('root path required')
    ^
TypeError: root path required
    at serveStatic (/usr/lib/node_modules/reveal-md/node_modules/serve-static/index.js:40:11)
    at startServer (/usr/lib/node_modules/reveal-md/lib/serve.js:49:58)
    at revealMarkdown (/usr/lib/node_modules/reveal-md/lib/index.js:22:5)
    at Object.<anonymous> (/usr/lib/node_modules/reveal-md/bin/cli.js:55:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by frankscholten** [comment]
@moretea This also didn't work when I checked out your latest commit https://github.com/ContainerSolutions/reveal-md/commit/e7835c5710661b377b63eb09f83b11a880104277. Can you have a look?

**Comment by idcrosby** [comment]
@frankscholten the path to the markdown needs to be passed in. Fixed here: https://github.com/ContainerSolutions/reveal-md/commit/515563ed0cc841a5478c38b8b2840bae90cf78b2

**Comment by frankscholten** [comment]
LGTM
